# Generated by Django 5.2.7 on 2025-11-02 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('ganancia', models.CharField(max_length=45)),
                ('alimentacion_gall', models.CharField(db_column='Alimentacion_gall', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'billetera',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('estado_cliente', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Gallina',
            fields=[
                ('idgallina', models.AutoField(db_column='idGallina', primary_key=True, serialize=False)),
                ('nom_gallina', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gallina',
            },
        ),
        migrations.CreateModel(
            name='Granjero',
            fields=[
                ('nom_granjero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gallina_idgallina', models.ForeignKey(db_column='Gallina_idGallina', on_delete=django.db.models.deletion.DO_NOTHING, to='huevo.gallina')),
            ],
            options={
                'db_table': 'granjero',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billetera_alimentacion_gall', models.ForeignKey(db_column='Billetera_Alimentacion_gall', on_delete=django.db.models.deletion.DO_NOTHING, to='huevo.billetera')),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Huevo',
            fields=[
                ('idhuevo', models.IntegerField(db_column='idHuevo', primary_key=True, serialize=False)),
                ('tamano', models.CharField(db_column='Tamano', max_length=10)),
                ('gallina_idgallina', models.ForeignKey(db_column='Gallina_idGallina', on_delete=django.db.models.deletion.DO_NOTHING, to='huevo.gallina')),
            ],
            options={
                'db_table': 'huevo',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_total', models.IntegerField(db_column='Stock_total', primary_key=True, serialize=False)),
                ('huevo_idhuevo', models.ForeignKey(db_column='Huevo_idHuevo', on_delete=django.db.models.deletion.DO_NOTHING, to='huevo.huevo')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('fecha_venta', models.DateTimeField(db_column='Fecha_venta', primary_key=True, serialize=False)),
                ('stock_stock_total', models.ForeignKey(db_column='Stock_Stock_total', on_delete=django.db.models.deletion.DO_NOTHING, to='huevo.stock')),
            ],
            options={
                'db_table': 'tienda',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('total_venta', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('cliente_idcliente', models.ForeignKey(db_column='Cliente_idCliente', on_delete=django.db.models.deletion.DO_NOTHING, to='huevo.cliente')),
                ('granjero_nom_granjero', models.ForeignKey(db_column='Granjero_nom_granjero', on_delete=django.db.models.deletion.DO_NOTHING, to='huevo.granjero')),
                ('tienda_fecha_venta', models.ForeignKey(db_column='Tienda_Fecha_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='huevo.tienda')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.AddField(
            model_name='billetera',
            name='venta_total_venta',
            field=models.ForeignKey(db_column='Venta_total_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='huevo.venta'),
        ),
        migrations.CreateModel(
            name='VentaHasHuevo',
            fields=[
                ('precio', models.CharField(blank=True, max_length=20, null=True)),
                ('id_vhh', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('huevo_idhuevo', models.ForeignKey(db_column='Huevo_idHuevo', on_delete=django.db.models.deletion.DO_NOTHING, to='huevo.huevo')),
                ('venta_total_venta', models.ForeignKey(db_column='Venta_total_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='huevo.venta')),
            ],
            options={
                'db_table': 'venta_has_huevo',
            },
        ),
    ]
